from __future__ import annotations

from datetime import datetime, timezone
import hashlib
from typing import Any

from connectors.base import BaseConnector
from shared.models import DefenderDetectionFindingEvent, Envelope, VendorExtension
from shared.models.mappers import build_connector_correlation, build_envelope


class _StubConnector(BaseConnector):
    provider_name = "stub"

    @property
    def provider(self) -> str:
        return self.provider_name

    def _now(self) -> datetime:
        return datetime.now(timezone.utc)

    async def fetch_events(self, query: dict) -> list[Envelope]:
        top = max(1, int(query.get("top", 1)))
        subject_prefix = str(query.get("subject_prefix", self.provider))

        events: list[Envelope] = []
        for index in range(top):
            event_id = f"{self.provider}-{self.tenant_id}-{index + 1}"
            payload = DefenderDetectionFindingEvent(
                event_type="defender.alert",
                activity_id=2004,
                activity_name="stub.fetch",
                alert_id=event_id,
                title=f"{subject_prefix}-{index + 1}",
                description="Generated by stub connector",
                severity_id=40,
                severity="medium",
                vendor_extensions={
                    "provider_event_type": VendorExtension(source=self.provider, value="stub"),
                    "source": VendorExtension(source=self.provider, value="stub_connector"),
                },
            )
            occurred_at = self._now()
            events.append(
                build_envelope(
                    tenant_id=self.tenant_id,
                    source_provider=self.provider,
                    occurred_at=occurred_at,
                    correlation=build_connector_correlation(
                        tenant_id=self.tenant_id,
                        event_name=payload.event_type,
                        correlation_id=event_id,
                        provider_event_id=event_id,
                    ),
                    payload=payload,
                    provider_event_id=event_id,
                    metadata={"query": query},
                )
            )
        return events

    def _mock_ticket_id(self, payload: dict[str, Any]) -> str:
        prefix = str(payload.get("project_key") or "SOC").upper()
        seed_source = f"{self.provider}:{self.tenant_id}:{payload.get('title') or payload.get('ticket_id') or 'stub'}"
        digest = hashlib.sha1(seed_source.encode("utf-8")).hexdigest()
        seed = int(digest[:8], 16)
        return f"{prefix}-{seed % 10000 + 1}"

    async def execute_action(self, action: str, payload: dict) -> dict:
        # Ticketing style actions
        if action in {"create_ticket", "create_issue"}:
            ticket_id = self._mock_ticket_id(payload)
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "ticket_id": ticket_id,
                "key": ticket_id,
                "status": "open",
                "details": "created by stub connector",
                "echo": payload,
            }

        if action in {"update_ticket", "update_issue"}:
            ticket_id = str(payload.get("ticket_id") or self._mock_ticket_id(payload))
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "ticket_id": ticket_id,
                "updated": True,
                "status": str(payload.get("fields", {}).get("status") or "updated").lower(),
                "details": "updated by stub connector",
                "echo": payload,
            }

        if action in {"close_ticket", "close_issue"}:
            ticket_id = str(payload.get("ticket_id") or self._mock_ticket_id(payload))
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "ticket_id": ticket_id,
                "closed": True,
                "status": "closed",
                "details": "closed by stub connector",
                "echo": payload,
            }

        if action in {"get_ticket", "get_issue"}:
            ticket_id = str(payload.get("ticket_id") or self._mock_ticket_id(payload))
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "id": ticket_id,
                "key": ticket_id,
                "fields": {
                    "summary": f"Stub issue for {self.provider}",
                    "description": "Generated by stub connector",
                    "priority": {"name": "Medium"},
                    "status": {"name": "Open"},
                    "assignee": {"emailAddress": "stub@example.com"},
                    "created": self._now().isoformat(),
                },
            }

        # Threat-intel style actions
        if action == "lookup_indicator":
            indicator = str(payload.get("indicator") or "")
            is_malicious = any(token in indicator.lower() for token in ["mal", "bad", "phish", "ransom"])
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "indicator": indicator,
                "is_malicious": is_malicious,
                "reputation_score": 0.9 if is_malicious else 0.1,
                "details": "stub threat intel result",
            }

        # Generic remediation actions used by SOC flows
        if action in {"isolate_device", "unisolate_device", "quarantine_file", "disable_user", "reset_password"}:
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "details": "stub action accepted",
                "submitted": True,
                "echo": payload,
            }

        if action == "get_device_context":
            device_id = str(payload.get("device_id") or "stub-device")
            return {
                "success": True,
                "provider": self.provider,
                "found": True,
                "device_id": device_id,
                "display_name": f"{self.provider}-{device_id}",
                "os_platform": "windows",
                "compliance_state": "compliant",
                "risk_score": "Low",
            }

        if action == "get_identity_risk":
            lookup_key = str(payload.get("lookup_key") or "unknown@example.com")
            high_risk = any(token in lookup_key.lower() for token in ["admin", "priv", "risk"])
            return {
                "success": True,
                "provider": self.provider,
                "found": True,
                "subject": lookup_key,
                "risk_level": "high" if high_risk else "low",
                "risk_state": "atRisk" if high_risk else "none",
                "risk_detail": "stub identity risk result",
            }

        return {
            "success": True,
            "action": action,
            "provider": self.provider,
            "details": "stub passthrough action",
            "echo": payload,
        }

    async def health_check(self) -> dict:
        return {
            "healthy": True,
            "provider": self.provider,
            "details": "stub connector ready",
            "mode": "stub",
            "checked_at": self._now().isoformat(),
        }


class CrowdStrikeConnector(_StubConnector):
    provider_name = "crowdstrike"


class SentinelOneConnector(_StubConnector):
    provider_name = "sentinelone"


class HaloItsmConnector(_StubConnector):
    provider_name = "halo_itsm"


class ServiceNowConnector(_StubConnector):
    provider_name = "servicenow"


class VirusTotalConnector(_StubConnector):
    provider_name = "virustotal"


class AbuseIpdbConnector(_StubConnector):
    provider_name = "abuseipdb"


class MispConnector(_StubConnector):
    provider_name = "misp"
