from __future__ import annotations

from datetime import datetime, timezone
import hashlib
from typing import Any

from connectors.base import BaseConnector
from shared.models import CanonicalEvent


class _StubConnector(BaseConnector):
    provider_name = "stub"

    @property
    def provider(self) -> str:
        return self.provider_name

    def _now(self) -> datetime:
        return datetime.now(timezone.utc)

    async def fetch_events(self, query: dict) -> list[CanonicalEvent]:
        top = max(1, int(query.get("top", 1)))
        event_type = str(query.get("event_type", f"{self.provider}.event"))
        subject_prefix = str(query.get("subject_prefix", self.provider))

        events: list[CanonicalEvent] = []
        for index in range(top):
            event_id = f"{self.provider}-{self.tenant_id}-{index + 1}"
            events.append(
                CanonicalEvent(
                    event_type=event_type,
                    tenant_id=self.tenant_id,
                    provider=self.provider,
                    external_event_id=event_id,
                    subject=f"{subject_prefix}-{index + 1}",
                    severity="medium",
                    occurred_at=self._now(),
                    payload={
                        "provider_event_type": "stub",
                        "source": "stub_connector",
                        "query": query,
                    },
                )
            )
        return events

    def _mock_ticket_id(self, payload: dict[str, Any]) -> str:
        prefix = str(payload.get("project_key") or "SOC").upper()
        seed_source = f"{self.provider}:{self.tenant_id}:{payload.get('title') or payload.get('ticket_id') or 'stub'}"
        digest = hashlib.sha1(seed_source.encode("utf-8")).hexdigest()
        seed = int(digest[:8], 16)
        return f"{prefix}-{seed % 10000 + 1}"

    async def execute_action(self, action: str, payload: dict) -> dict:
        # Ticketing style actions
        if action in {"create_ticket", "create_issue"}:
            ticket_id = self._mock_ticket_id(payload)
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "ticket_id": ticket_id,
                "key": ticket_id,
                "status": "open",
                "details": "created by stub connector",
                "echo": payload,
            }

        if action in {"update_ticket", "update_issue"}:
            ticket_id = str(payload.get("ticket_id") or self._mock_ticket_id(payload))
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "ticket_id": ticket_id,
                "updated": True,
                "status": str(payload.get("fields", {}).get("status") or "updated").lower(),
                "details": "updated by stub connector",
                "echo": payload,
            }

        if action in {"close_ticket", "close_issue"}:
            ticket_id = str(payload.get("ticket_id") or self._mock_ticket_id(payload))
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "ticket_id": ticket_id,
                "closed": True,
                "status": "closed",
                "details": "closed by stub connector",
                "echo": payload,
            }

        if action in {"get_ticket", "get_issue"}:
            ticket_id = str(payload.get("ticket_id") or self._mock_ticket_id(payload))
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "id": ticket_id,
                "key": ticket_id,
                "fields": {
                    "summary": f"Stub issue for {self.provider}",
                    "description": "Generated by stub connector",
                    "priority": {"name": "Medium"},
                    "status": {"name": "Open"},
                    "assignee": {"emailAddress": "stub@example.com"},
                    "created": self._now().isoformat(),
                },
            }

        # Threat-intel style actions
        if action == "lookup_indicator":
            indicator = str(payload.get("indicator") or "")
            is_malicious = any(token in indicator.lower() for token in ["mal", "bad", "phish", "ransom"])
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "indicator": indicator,
                "is_malicious": is_malicious,
                "reputation_score": 0.9 if is_malicious else 0.1,
                "details": "stub threat intel result",
            }

        # Generic remediation actions used by SOC flows
        if action in {"isolate_device", "unisolate_device", "quarantine_file", "disable_user", "reset_password"}:
            return {
                "success": True,
                "action": action,
                "provider": self.provider,
                "details": "stub action accepted",
                "submitted": True,
                "echo": payload,
            }

        return {
            "success": True,
            "action": action,
            "provider": self.provider,
            "details": "stub passthrough action",
            "echo": payload,
        }

    async def health_check(self) -> dict:
        return {
            "healthy": True,
            "provider": self.provider,
            "details": "stub connector ready",
            "mode": "stub",
            "checked_at": self._now().isoformat(),
        }


class CrowdStrikeConnector(_StubConnector):
    provider_name = "crowdstrike"


class SentinelOneConnector(_StubConnector):
    provider_name = "sentinelone"


class HaloItsmConnector(_StubConnector):
    provider_name = "halo_itsm"


class ServiceNowConnector(_StubConnector):
    provider_name = "servicenow"


class VirusTotalConnector(_StubConnector):
    provider_name = "virustotal"


class AbuseIpdbConnector(_StubConnector):
    provider_name = "abuseipdb"


class MispConnector(_StubConnector):
    provider_name = "misp"
